[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@openzeppelin/=node_modules/@openzeppelin",
"abdk-libraries-solidity/=node_modules/abdk-libraries-solidity"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
